# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

use_frameworks!

target 'SKPhotoBrowserExample' do
  # Pods for SKPhotoBrowserExample
  pod 'SDWebImage', '~>3.8'

end
